name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  docker_build_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.SECRET }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: "frontend"
          push: true
          tags: ghcr.io/benedict-cs/k8s-hw3-frontend:${{ github.sha }}

  docker_build_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.SECRET }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: "backend"
          push: true
          tags: ghcr.io/benedict-cs/k8s-hw3-backend:${{ github.sha }}

  deploy:
    needs: [docker_build_frontend, docker_build_backend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.20.2/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
      - run: |
          yq eval -i 'select(.kind == "Deployment" and .metadata.name == "k8s-hw3-backend").spec.template.spec.containers[] |= select(.name == "k8s-hw3-backend").image = "ghcr.io/benedict-cs/k8s-backend:${{ github.sha }}"' ./K8s/deploys.yaml
          yq eval -i 'select(.kind == "Deployment" and .metadata.name == "k8s-hw3-frontend").spec.template.spec.containers[] |= select(.name == "k8s-hw3-frontend").image = "ghcr.io/benedict-cs/k8s-frontend:${{ github.sha }}"' ./K8s/deploys.yaml
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          version: "latest"
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true


      - name: Configure kubectl
        env:
          KUBECONFIG: ${{ secrets.KUBE }}
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE }}"  > $HOME/.kube/config
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./K8s/deploys.yaml
          kubectl apply -f ./K8s/services.yaml
          kubectl apply -f ./K8s/ingress.yaml
      - name: Debug
        run: |
          echo "Contents of K8s Deployment YAML:"
          cat ./K8s/deploys.yaml
          echo "Current Pods in the Kubernetes Cluster:"
          kubectl get pods
          kubectl logs db-deployment-78b8869bd6-ffcgc 
          kubectl logs frontend-deployment-5cf569cbc5-csjdq
          kubectl logs backend-deployment-5d49984b75-zt9xl