name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.SECRET }}

      - name: Build and Push Frontend Docker Image
        uses: docker/build-push-action@v5
        with:
          context: "frontend"
          push: true
          tags: ghcr.io/benedict-cs/k8s-frontend:${{ github.sha }}

      - name: Build and Push Backend Docker Image
        uses: docker/build-push-action@v5
        with:
          context: "backend"
          push: true
          tags: ghcr.io/benedict-cs/k8s-backend:${{ github.sha }}

      - name: Setup GCP
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Prepare Kubernetes Configuration
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config
          mkdir -p $HOME/.kube
          mv $HOME/.kube/config $HOME/.kube/config
          kubectl config view

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./K8s/deploys.yaml
          kubectl apply -f ./K8s/services.yaml
          kubectl apply -f ./K8s/ingress.yaml
          kubectl get pods
          kubectl get svc

      - name: Debug Connection Issues
        if: failure()
        run: |
          echo "Failed to connect to Kubernetes cluster."
          kubectl config view
          kubectl cluster-info
