name: Continuous Integration

on:
  push:
    branches:
      - main
      - action

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install
        working-directory: ./backend

      - name: Generate new coverage report
        run: |
          npm run test --coverage
          ls -l ./coverage  # 新增的步驟來列出 coverage 目錄的內容
          node ./coverage/calCoverage.js
        working-directory: ./backend

      - name: Check and compare coverage
        run: node ./coverage/checkCoverage.js
        working-directory: ./backend

      - name: Upload coverage to Artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ./backend/coverage/lcov-report/

      - name: Format JavaScript and TypeScript files
        run: npx prettier --write "**/*.{js,ts}"
        working-directory: ./backend

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "::set-output name=changes_detected::true"
        working-directory: ./backend

      - name: Commit changes
        if: steps.git-check.outputs.changes_detected == 'true'
        run: |
          git add .
          git config user.name 'Benedict-CS'
          git config user.email 'benedicttiong.cs@gmail.com'
          git commit -m "Apply code formatting"
          git push
        working-directory: ./backend
